baseURL = "/"
languageCode = "en-us"
title = "Tjalling Tolle"
#googleAnalytics = ""
#disqusShortname = ""
#paginate = 2
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

[blackfriday]
	extensions = ["hardLineBreak"]

[params]
	banner = "/images/banner.png"
	logo = "/images/logo.png"
	name = "Tjalling Tolle"
	description = "Portfolio of Tjalling Tolle"
	bio = "Creative Technologist"
