baseURL = "/"
languageCode = "en-us"
title = "Tjalling Tolle"
#googleAnalytics = ""
#disqusShortname = ""
#paginate = 2
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

[blackfriday]
	extensions = ["hardLineBreak"]

[params]
	author = "Tjalling Tolle"
	logo = "/images/logo.png"
	banner = "/images/banner.png"
	description = "Portfolio of Tjalling Tolle, Creative Technologist, Designer and Developer."
	subtitle = "Creative Technologist"
